name: hosting-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          #ssh_private_key: ${{ secrets.SFTP_KEY }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './*'
          remote_path: '/var/www/html/'
          sftp_only: true