name: hosting-deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 48153
          local_path: './*'
          remote_path: '/var/www/html/'
          sftp_only: true
          password: ${{ secrets.SFTP_PASSWORD }}