name: hosting-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy code
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          # Use either private key or password.
          ssh_private_key: ${{ secrets.SFTP_KEY }}
          #password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './*'
          remote_path: '/var/www/html/'
          sftp_only: true
      - name: Deploy code
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_KEY }}
          passphrase: ${{ secrets.SFTP_PASSWORD }}
          uploads: |
            ./* => /var/www/html
          ignore: |
            !README.md
            !.htaccess